In [2]:
from pycaret.datasets import get_data

In [ ]:
data1 = get_data(dataset = 'traffic')

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,Rush Hour,traffic_volume
0,NaN,288.28,0.0,0.0,40,Clouds,1,5545
1,NaN,289.36,0.0,0.0,75,Clouds,0,4516
2,NaN,289.58,0.0,0.0,90,Clouds,0,4767
3,NaN,290.13,0.0,0.0,90,Clouds,0,5026
4,NaN,291.14,0.0,0.0,75,Clouds,0,4918

Queremos predecir cuanto trafico vamos a tener dependiendo de ciertas variables del clima. La variable target es traffic y vemos que es un modelo de regresion porque se trata de predecir una variable continua (numerica).
Como sabemos que es una regresion importamos la siguiente libreria

In [4]:
from pycaret.regression import *

In [5]:
dataset = setup(data = data1, target = 'traffic_volume', session_id = 123)
#en los entornos no productivos o de desarrollo se recomieda siempre usar el session_id con cualquier numero.
#Esta es la variable que me inicializa el generador de numeros aleatorios. Y si le doy un numero el generador siempre va a tener
#el mismo comportamiento. Por lo tanto, si yo vuelvo a correr el setup, el resultado va a ser el mismo.
#En entornos productivos, se recomienda no usar el session_id, para que el generador de numeros aleatorios tenga un comportamiento diferente
#en cada ejecucion. Esto es para que el modelo no se vea afectado por el mismo comportamiento de los numeros aleatorios.

In [6]:
best = compare_models()
#El compare_models me va a devolver el mejor modelo.

Processing:   0%|          | 0/81 [00:00<?, ?it/s]

In [8]:
tuned_best = tune_model(estimator = best)
#El tune_model me va a devolver el mejor modelo ajustado. Es para optimizarle los hiperparametros al mejor modelo

Initiated  . . . . . . . . . . . . . . . . . .              11:59:58
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [9]:
final_model = finalize_model(estimator = tuned_best)
#El finalize_model me va a devolver el mejor modelo ajustado y entrenado. Es para que yo pueda usar el modelo para hacer predicciones

In [ ]:
save_model(model = final_model, model_name = 'prueba_pycaret.pkl')
#Guardamos el modelo listo para pasar a produccion

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['temp', 'rain_1h', 'snow_1h',
                                              'clouds_all', 'Rush Hour'],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=['holiday', 'weather_main'],
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('onehot_encoding',
                  TransformerWrapper(include=['holiday', 'weather_main'],
                                     transformer=OneHotEncoder(cols=['holiday',
                                                                     'weather_main'],
                                                               handle_missing='return_nan',
                                                               use_cat_names=True))),
                 ('clean_column_names',
                  TransformerWrapper(transformer=CleanColumnNames())),
                 ('actual_estimator',
                  LGBMRegressor(n_jobs=-1, random_state=123))]),
 'prueba_pycaret.pkl.pkl')